name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow secara manual dari GitHub

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build Android Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk berkah-sekar.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v7
        with:
          name: berkah-sekar.apk
          path: berkah-sekar.apk
